/**
 * Unified score computation engine.
 * Used by BOTH admin getScoreResults AND user getPublicResults.
 *
 * Key guarantees:
 * 1. Scorer's CURRENT identity/department must match a current rate_target_rule.
 *    If identity changed, old records under the old identity are excluded.
 * 2. Template config signature must match current configuration.
 *    Stale template records are excluded.
 * 3. requireAllComplete is respected — if a scorer hasn't finished all
 *    required targets under a clause, their scores are excluded.
 * 4. Scores are grouped by (targetId, scorerCategoryKey, templateId) —
 *    same 3-D grouping used by admin overview.
 * 5. Group-level calc method (weighted_average / trim_extremes) is applied
 *    identically for admin and user views.
 */
const { safeString, toNumber, roundScore } = require('./helpers');
const pool = require('../config/db');

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

// Must match EXACTLY the format generated by buildTemplateConfigSignature in getScoreResults
// (the same function that wrote template_config_signature into score_records)
// Uses question COUNT (not full parameters) so score-range changes don't invalidate records.
function buildTemplateSignature(configs, templatesById) {
  return (configs || [])
    .map(function(config) {
      var template = templatesById.get(safeString(config.template_id));
      if (!template || !Array.isArray(template.questions) || !template.questions.length) return '';
      var qCount = template.questions.length;
      var method = safeString(config.calculation_method || 'weighted_average');
      var trimH = Number(config.trim_high_count || 0);
      var trimL = Number(config.trim_low_count || 0);
      return safeString(config.template_id) + '[' + qCount + '|' + method + '|' + trimH + '|' + trimL + ']';
    })
    .filter(Boolean)
    .join('|');
}

/**
 * Normalize a legacy (full-parameter) signature to the structure-only format.
 * Legacy: templateId[min:start:max:step,...|method|trimH|trimL]
 * Structure: templateId[questionCount|method|trimH|trimL]
 */
function normalizeSignatureToStructure(sig) {
  if (!sig) return null;
  var parts = [];
  var depth = 0, start = 0;
  for (var i = 0; i < sig.length; i++) {
    if (sig[i] === '[') depth++;
    else if (sig[i] === ']') depth--;
    else if (sig[i] === '|' && depth === 0) { parts.push(sig.substring(start, i)); start = i + 1; }
  }
  parts.push(sig.substring(start));

  var normalized = parts.map(function(part) {
    var bracketIdx = part.indexOf('[');
    if (bracketIdx === -1) return part;
    var templateId = part.substring(0, bracketIdx);
    var inner = part.substring(bracketIdx + 1, part.length - 1);
    var innerParts = inner.split('|');
    if (innerParts.length < 4) return part;
    var methodAndTrim = innerParts.slice(-3).join('|');
    var beforeMethod = innerParts.slice(0, -3).join('|');
    var questionCount;
    if (beforeMethod.indexOf(':') !== -1) {
      questionCount = beforeMethod.split(',').filter(function(s) { return s.indexOf(':') !== -1; }).length;
    } else {
      questionCount = parseInt(beforeMethod, 10);
      if (isNaN(questionCount)) return part;
    }
    return templateId + '[' + questionCount + '|' + methodAndTrim + ']';
  });
  return normalized.join('|');
}
function applyCalcMethod(scores, weight, method, trimH, trimL) {
  if (!scores.length) return { averageScore: 0, contributionScore: 0 };
  if (method === 'trim_extremes') {
    const totalTrim = (trimH || 0) + (trimL || 0);
    if (scores.length < totalTrim) return { averageScore: 0, contributionScore: 0 };
    const sorted = scores.slice().sort((a, b) => a - b);
    const trimmed = sorted.slice(trimL || 0, scores.length - (trimH || 0));
    if (!trimmed.length) return { averageScore: 0, contributionScore: 0 };
    const avg = trimmed.reduce((s, v) => s + v, 0) / trimmed.length;
    return { averageScore: roundScore(avg), contributionScore: roundScore(avg * weight) };
  }
  const avg = scores.reduce((s, v) => s + v, 0) / scores.length;
  return { averageScore: roundScore(avg), contributionScore: roundScore(avg * weight) };
}

// ---------------------------------------------------------------------------
// Main entry point
// ---------------------------------------------------------------------------

/**
 * @param {string} activityId
 * @param {string} orgId
 * @param {object} [options]
 * @param {Set<string>} [options.visibleTargetIds] - restrict to these targets (user view)
 * @returns {Promise<Map<string, {finalScore:number, details:object[]}>>}
 */
async function computeValidScoreMap(activityId, orgId, options = {}) {
  const { visibleTargetIds } = options;

  // ── 1. Load all current data ──────────────────────────────────────────
  const [
    [hrRows],
    [ruleRows],
    [recordRows],
    [tplRows],
    [questionRows]
  ] = await Promise.all([
    pool.query('SELECT * FROM hr_info WHERE org_id = ?', [orgId]),
    pool.query('SELECT * FROM rate_target_rules WHERE activity_id = ? AND org_id = ?', [activityId, orgId]),
    pool.query('SELECT * FROM score_records WHERE activity_id = ? AND org_id = ?', [activityId, orgId]),
    pool.query('SELECT * FROM score_question_templates'),
    pool.query('SELECT * FROM score_questions ORDER BY template_id, sort_order')
  ]);

  if (!ruleRows.length) return new Map();

  // ── 2. Build current rule structures ──────────────────────────────────
  const ruleIds = ruleRows.map(r => `'${r.id}'`);
  const [clauseRows] = await pool.query(
    `SELECT * FROM rate_rule_clauses WHERE rule_id IN (${ruleIds.join(',')}) AND org_id = ?`,
    [orgId]
  );
  const clauseIds = clauseRows.map(c => `'${c.id}'`);
  let configRows = [];
  if (clauseIds.length) {
    [configRows] = await pool.query(
      `SELECT * FROM clause_template_configs WHERE clause_id IN (${clauseIds.join(',')}) AND org_id = ?`,
      [orgId]
    );
  }

  // Build lookup maps
  const hrById = new Map(hrRows.map(h => [safeString(h.id), h]));
  const questionsByTemplate = new Map();
  questionRows.forEach(q => {
    if (!questionsByTemplate.has(q.template_id)) questionsByTemplate.set(q.template_id, []);
    questionsByTemplate.get(q.template_id).push(q);
  });

  // Build templatesById map for signature generation (must match getScoreResults format)
  const templatesById = new Map();
  tplRows.forEach(t => {
    const tid = safeString(t.id);
    if (!tid) return;
    const qs = questionsByTemplate.get(tid) || [];
    templatesById.set(tid, {
      id: tid,
      name: safeString(t.name),
      questionCount: qs.length,
      questions: qs.map(q => ({
        question: q.question,
        scoreLabel: q.score_label,
        minValue: Number(q.min_value),
        startValue: Number(q.start_value),
        maxValue: Number(q.max_value),
        stepValue: Number(q.step_value)
      }))
    });
  });

  const configsByClause = new Map();
  configRows.forEach(c => {
    if (!configsByClause.has(c.clause_id)) configsByClause.set(c.clause_id, []);
    configsByClause.get(c.clause_id).push(c);
  });

  // Build rule lookup: ruleId -> { departmentId, identityId, allowSelfAssessment, clauses[] }
  const ruleByKey = new Map(); // key: "departmentId::identityId"
  const ruleById = new Map();
  ruleRows.forEach(r => {
    const deptId = safeString(r.scorer_department_id);
    const identId = safeString(r.scorer_identity_id);
    const key = `${deptId}::${identId}`;

    const clauses = clauseRows
      .filter(c => c.rule_id === r.id)
      .map(c => {
        const configs = (configsByClause.get(c.id) || []).sort((a, b) => (a.sort_order || 0) - (b.sort_order || 0));
        return {
          id: c.id,
          scopeType: safeString(c.scope_type),
          targetIdentityId: safeString(c.target_identity_id || ''),
          requireAllComplete: !!(c.require_all_complete),
          configs,
          signature: buildTemplateSignature(configs, templatesById)
        };
      })
      .filter(c => c.configs.length > 0); // skip clauses without template configs

    const ruleObj = {
      id: r.id,
      departmentId: deptId,
      identityId: identId,
      key,
      allowSelfAssessment: !!(r.allow_self_assessment),
      clauses
    };

    ruleByKey.set(key, ruleObj);
    ruleById.set(r.id, ruleObj);
  });

  // ── 2b. Build expected-by-count, scorer-expected-count, and submitted-by-target ──
  // Only the heavy pre-indexing + ruleRows loop is guarded by includeCounts.
  // The Map declarations and addSubmittedPair are always present (negligible cost).
  const expectedByCount = new Map();     // targetId -> number
  const scorerExpectedCount = new Map(); // scorerKey -> number
  const submittedByTarget = new Map();   // targetId -> Set<scorerKey>

  function addSubmittedPair(tid, sk) {
    if (!submittedByTarget.has(tid)) submittedByTarget.set(tid, new Set());
    submittedByTarget.get(tid).add(sk);
  }

  if (options.includeCounts) {

  // Pre-index HR for O(1) scope candidate lookup
  var hrByDept = new Map();
  var hrByIdentity = new Map();
  hrRows.forEach(function (h) {
    var did = safeString(h.department_id);
    var iid = safeString(h.identity_id);
    if (!hrByDept.has(did)) hrByDept.set(did, []);
    hrByDept.get(did).push(h);
    if (!hrByIdentity.has(iid)) hrByIdentity.set(iid, []);
    hrByIdentity.get(iid).push(h);
  });

  // Index HR by rule key (department::identity) for O(1) scorer lookup
  var hrByRuleKey = new Map();
  hrRows.forEach(function (h) {
    var key = safeString(h.department_id) + '::' + safeString(h.identity_id);
    if (!hrByRuleKey.has(key)) hrByRuleKey.set(key, []);
    hrByRuleKey.get(key).push(safeString(h.id));
  });

  // Index HR by (department, work_group) for per-WG scope resolution
  var hrByDeptWGMap = new Map();
  hrRows.forEach(function (h) {
    var did = safeString(h.department_id);
    var wid = safeString(h.work_group_id);
    if (!hrByDeptWGMap.has(did)) hrByDeptWGMap.set(did, new Map());
    var inner = hrByDeptWGMap.get(did);
    if (!inner.has(wid)) inner.set(wid, []);
    inner.get(wid).push(safeString(h.id));
  });

  ruleRows.forEach(function (r) {
    var deptId = safeString(r.scorer_department_id);
    var identId = safeString(r.scorer_identity_id);
    var ruleKey = deptId + '::' + identId;
    var rule = ruleByKey.get(ruleKey);
    if (!rule) return;

    var scorerIds = hrByRuleKey.get(ruleKey) || [];
    if (!scorerIds.length) return;
    var scorerIdSet = new Set(scorerIds);
    var allowSelf = rule.allowSelfAssessment;

    rule.clauses.forEach(function (clause) {
      var st = clause.scopeType;
      var targetIdentityId = clause.targetIdentityId;

      // ── Work-group scopes: handle per-WG (O(unique_WGs × (targets + scorers))) ──
      if (st === 'same_work_group_identity' || st === 'same_work_group_all') {
        var wgInner = hrByDeptWGMap.get(deptId);
        if (!wgInner) return;
        wgInner.forEach(function (wgMemberIds, wgId) {
          // Scorers in this WG
          var wgScorerIds = [];
          scorerIds.forEach(function (sid) {
            var h = hrById.get(sid);
            if (h && safeString(h.work_group_id) === wgId) wgScorerIds.push(sid);
          });
          if (!wgScorerIds.length) return;

          // Targets in this WG (filter by identity if scope requires)
          var wgTargetIds = wgMemberIds;
          if (st === 'same_work_group_identity' && targetIdentityId) {
            wgTargetIds = wgTargetIds.filter(function (tid) {
              var h = hrById.get(tid);
              return h && safeString(h.identity_id) === targetIdentityId;
            });
          }
          if (!wgTargetIds.length) return;

          var wgScorerSet = new Set(wgScorerIds);
          var wgTargetSet = new Set(wgTargetIds);
          var scorerN = wgScorerIds.length;
          var targetN = wgTargetIds.length;

          // O(targets): per-target count = N_scorers_in_WG (minus self if applicable)
          wgTargetIds.forEach(function (tid) {
            var cnt = scorerN;
            if (!allowSelf && wgScorerSet.has(tid)) cnt--;
            expectedByCount.set(tid, (expectedByCount.get(tid) || 0) + cnt);
          });

          // O(scorers): per-scorer count = N_targets_in_WG (minus self if applicable)
          wgScorerIds.forEach(function (sid) {
            var cnt = targetN;
            if (!allowSelf && wgTargetSet.has(sid)) cnt--;
            scorerExpectedCount.set(sid, (scorerExpectedCount.get(sid) || 0) + cnt);
          });
        });
        return;
      }

      // ── Non-work-group scopes: O(targets + scorers) ──
      var targets;
      if (st === 'all_people') {
        targets = hrRows;
      } else if (st === 'identity_only') {
        targets = hrByIdentity.get(targetIdentityId) || [];
      } else if (st === 'same_department_identity') {
        targets = hrByDept.get(deptId) || [];
        if (targetIdentityId) {
          targets = targets.filter(function (hr) { return safeString(hr.identity_id) === targetIdentityId; });
        }
      } else if (st === 'same_department_all') {
        targets = hrByDept.get(deptId) || [];
      } else {
        return;
      }

      // Global targetIdentityId filter for scopes that don't pre-filter (matches record validation)
      if (targetIdentityId && (st === 'all_people' || st === 'same_department_all')) {
        targets = targets.filter(function (hr) { return safeString(hr.identity_id) === targetIdentityId; });
      }

      var targetIds = targets.map(function (h) { return safeString(h.id); });
      if (!targetIds.length) return;

      var targetIdSet = new Set(targetIds);
      var scorerN = scorerIds.length;
      var targetN = targetIds.length;

      // O(targets): per-target count = N_scorers (minus self if applicable)
      targetIds.forEach(function (tid) {
        var cnt = scorerN;
        if (!allowSelf && scorerIdSet.has(tid)) cnt--;
        expectedByCount.set(tid, (expectedByCount.get(tid) || 0) + cnt);
      });

      // O(scorers): per-scorer count = N_targets (minus self if applicable)
      scorerIds.forEach(function (sid) {
        var cnt = targetN;
        if (!allowSelf && targetIdSet.has(sid)) cnt--;
        scorerExpectedCount.set(sid, (scorerExpectedCount.get(sid) || 0) + cnt);
      });
    });
  });

  } // end if (options.includeCounts)

  // ── 3. Load all answers (batch) ───────────────────────────────────────
  let answerMap = new Map(); // recordId -> [{questionIndex, score}]
  if (recordRows.length) {
    const recordIds = recordRows.map(r => `'${r.id}'`);
    const [answerRows] = await pool.query(
      `SELECT * FROM score_answers WHERE record_id IN (${recordIds.join(',')}) AND org_id = ? ORDER BY record_id, question_index`,
      [orgId]
    );
    // Normalize: group answers by record_id with zero-index detection (match getRecordTemplateScores logic)
    const rawByRecord = new Map();
    answerRows.forEach(a => {
      if (!rawByRecord.has(a.record_id)) rawByRecord.set(a.record_id, []);
      rawByRecord.get(a.record_id).push(a);
    });
    rawByRecord.forEach((rawAnswers, recordId) => {
      const hasZero = rawAnswers.some(a => a.question_index === 0);
      answerMap.set(recordId, rawAnswers.map(a => ({
        questionIndex: hasZero ? (a.question_index + 1) : a.question_index,
        score: toNumber(a.score, 0)
      })));
    });
  }

  // ── 4. Validate records & compute template scores ─────────────────────
  // Group: (targetId, scorerCategoryKey, templateId) -> { scores[], weight, method, trimH, trimL }

  const calculationMap = new Map();
  const scorerCompletionMap = new Map(); // scorerKey -> Set<taskKey> for requireAllComplete
  const repairMap = new Map(); // recordId -> currentSig (for auto-repair old records)

  // Diagnostic counters
  let diag_total = 0, diag_skipped_visible = 0, diag_skipped_noHr = 0, diag_skipped_noRule = 0;
  let diag_skipped_noScope = 0, diag_skipped_self = 0, diag_skipped_sig = 0, diag_accepted = 0;
  const diag_sigDetails = []; // first few sig mismatches

  // First pass: validate and collect
  for (const record of recordRows) {
    diag_total++;
    const targetId = safeString(record.target_id);
    const ruleId = safeString(record.rule_id);

    // Optionally filter by visible targets (user view)
    if (visibleTargetIds && !visibleTargetIds.has(targetId)) { diag_skipped_visible++; continue; }

    // (a) Scorer's CURRENT hr_info must exist
    const scorerHr = hrById.get(safeString(record.scorer_id));
    if (!scorerHr) { diag_skipped_noHr++; continue; } // scorer no longer exists — exclude record

    // (b) Scorer's CURRENT (department, identity) must match a current rule
    const scorerDeptId = safeString(scorerHr.department_id);
    const scorerIdentId = safeString(scorerHr.identity_id);
    const scorerRuleKey = `${scorerDeptId}::${scorerIdentId}`;
    const currentRule = ruleByKey.get(scorerRuleKey);

    // If scorer's identity changed and they no longer match any rule, exclude
    if (!currentRule) { diag_skipped_noRule++; continue; }

    // If record's rule_id doesn't match the current rule (identity changed),
    // use the current rule instead of the historical one
    const effectiveRule = currentRule;

    // (c) Target must be in scope of at least one clause
    const targetHr = hrById.get(targetId);
    if (!targetHr) continue; // target no longer exists

    const targetDeptId = safeString(targetHr.department_id);
    const targetIdentId = safeString(targetHr.identity_id);
    const targetWgId = safeString(targetHr.work_group_id);

    // Find matching clause
    let matchedClause = null;
    for (const clause of effectiveRule.clauses) {
      if (clause.targetIdentityId && clause.targetIdentityId !== targetIdentId) continue;

      let inScope = false;
      if (clause.scopeType === 'all_people') inScope = true;
      else if (clause.scopeType === 'identity_only') inScope = true;
      else if (clause.scopeType === 'same_department_identity' || clause.scopeType === 'same_department_all')
        inScope = targetDeptId === scorerDeptId;
      else if (clause.scopeType === 'same_work_group_identity' || clause.scopeType === 'same_work_group_all')
        inScope = targetDeptId === scorerDeptId && targetWgId === safeString(scorerHr.work_group_id);

      if (inScope) {
        matchedClause = clause;
        break;
      }
    }
    if (!matchedClause) { diag_skipped_noScope++; continue; } // target not in scope of current rule

    // (d) Self-assessment check
    if (!effectiveRule.allowSelfAssessment && safeString(record.scorer_id) === targetId) { diag_skipped_self++; continue; }

    // (e) Template signature check — build current signature and compare structure
    const currentSig = matchedClause.signature;
    const recordSig = safeString(record.template_config_signature);
    // Normalize legacy signatures to structure-only format for comparison
    const recordSigNormalized = normalizeSignatureToStructure(recordSig) || recordSig;
    // Compat: old records without signature → accept and mark for auto-repair
    // Records with matching structure → accept
    // Records with mismatched structure → accept but flag as sigStale (matching old
    // admin calculation path behavior which includes stale records in computation).
    // The template scores are extracted using the CURRENT matched clause's configs,
    // which is what getRecordTemplateScores in results.js also does.
    const sigStale = !!(currentSig && recordSigNormalized && currentSig !== recordSigNormalized);
    if (sigStale) {
      diag_skipped_sig++;
      if (diag_sigDetails.length < 5) diag_sigDetails.push({ recordId: record.id, currentSig: currentSig.substring(0, 120), recordSig: recordSigNormalized.substring(0, 120) });
    }
    const needsRepair = currentSig && (!recordSig || normalizeSignatureToStructure(recordSig) !== recordSig); // old format or no signature
    if (needsRepair) repairMap.set(record.id, currentSig);
    diag_accepted++;

    // (f) Build template scores
    const answers = answerMap.get(record.id) || [];
    let cursor = 0;
    const templateScores = [];

    for (const cfg of matchedClause.configs) {
      const templateId = safeString(cfg.template_id);
      const questions = questionsByTemplate.get(templateId) || [];
      let tplScore = 0;
      for (let qi = 0; qi < questions.length; qi++) {
        const ans = answers.find(a => a.questionIndex === cursor + qi + 1);
        if (ans) tplScore += ans.score;
      }
      cursor += questions.length;

      const scorerCategoryKey = `${safeString(effectiveRule.departmentId)}::${safeString(effectiveRule.identityId)}`;
      const groupKey = `${targetId}||${scorerCategoryKey}||${templateId}`;

      if (!calculationMap.has(groupKey)) {
        calculationMap.set(groupKey, {
          targetId,
          scorerCategoryKey,
          templateId,
          clauseId: matchedClause.id,
          ruleId: effectiveRule.id,
          weight: toNumber(cfg.weight, 1),
          method: safeString(cfg.calculation_method) || 'weighted_average',
          trimHigh: Number(cfg.trim_high_count || 0),
          trimLow: Number(cfg.trim_low_count || 0),
          scores: [],
          scorerKey: safeString(record.scorer_id)
        });
      }
      calculationMap.get(groupKey).scores.push(tplScore);

      templateScores.push({ templateId, tplScore, cfg });
    }

    // Track valid submission for overview counts (only when needed)
    if (options.includeCounts) addSubmittedPair(targetId, safeString(record.scorer_id));

    // Track for requireAllComplete
    if (matchedClause.requireAllComplete && templateScores.length > 0) {
      const scorerKey = safeString(record.scorer_id);
      const clauseTaskKey = `${effectiveRule.id}::${matchedClause.id}::${scorerKey}::${targetId}`;
      if (!scorerCompletionMap.has(effectiveRule.id + '::' + matchedClause.id + '::' + scorerKey)) {
        scorerCompletionMap.set(effectiveRule.id + '::' + matchedClause.id + '::' + scorerKey, new Set());
      }
      scorerCompletionMap.get(effectiveRule.id + '::' + matchedClause.id + '::' + scorerKey).add(targetId);
    }
  }

  // ── 5. requireAllComplete: determine which scorer-clause combos are complete ──
  const invalidScorerClauseKeys = new Set();
  scorerCompletionMap.forEach((completedTargets, key) => {
    // Parse key: ruleId::clauseId::scorerKey
    const parts = key.split('::');
    const ruleId = parts[0];
    const clauseId = parts[1];
    const scorerKey = parts[2]; // scorer's hr_id

    const rule = ruleById.get(ruleId);
    if (!rule) return;
    const clause = rule.clauses.find(c => c.id === clauseId);
    if (!clause || !clause.requireAllComplete) return;

    // Find all expected targets for this scorer under this clause.
    // Must account for work-group scoping: for same_work_group_* scopes,
    // only targets in the scorer's work group are expected.
    const scorerDeptId = rule.departmentId;
    // Look up the scorer's work_group_id for WG-scope filtering
    const scorerHr = scorerKey ? hrById.get(scorerKey) : null;
    const scorerWgId = scorerHr ? safeString(scorerHr.work_group_id) : '';

    let expectedTargetCount = 0;
    hrRows.forEach(hr => {
      const tid = safeString(hr.identity_id);
      const tdid = safeString(hr.department_id);
      if (clause.targetIdentityId && clause.targetIdentityId !== tid) return;
      let match = false;
      if (clause.scopeType === 'all_people' || clause.scopeType === 'identity_only') match = true;
      else if (clause.scopeType === 'same_department_identity' || clause.scopeType === 'same_department_all')
        match = tdid === scorerDeptId;
      else if (clause.scopeType === 'same_work_group_identity' || clause.scopeType === 'same_work_group_all')
        match = tdid === scorerDeptId && safeString(hr.work_group_id) === scorerWgId;
      if (match) expectedTargetCount++;
    });

    if (completedTargets.size < expectedTargetCount) {
      invalidScorerClauseKeys.add(key);
    }
  });

  // ── 6. Apply calc methods and compute final scores ────────────────────
  const finalScoreMap = new Map();

  calculationMap.forEach((item, groupKey) => {
    // Check requireAllComplete exclusion: a scorer who hasn't completed all
    // required targets for a specific clause should have that clause's scores excluded.
    // The invalidScorerClauseKeys set stores keys in the format ruleId::clauseId::scorerKey.
    if (invalidScorerClauseKeys.size > 0) {
      const itemClauseKey = `${item.ruleId || ''}::${item.clauseId || ''}::${item.scorerKey}`;
      if (invalidScorerClauseKeys.has(itemClauseKey)) return;
    }

    if (!item.scores.length) return;
    const result = applyCalcMethod(item.scores, item.weight, item.method, item.trimHigh, item.trimLow);
    const current = finalScoreMap.get(item.targetId) || { finalScore: 0, contributorCount: 0 };
    current.finalScore = roundScore(current.finalScore + result.contributionScore);
    current.contributorCount += 1;
    finalScoreMap.set(item.targetId, current);
  });

  // ── Auto-repair: update old records with current template signatures ──
  if (repairMap.size > 0) {
    const repairEntries = Array.from(repairMap.entries());
    // Fire-and-forget: don't block the response
    Promise.all(repairEntries.map(([recordId, sig]) =>
      pool.query('UPDATE score_records SET template_config_signature = ? WHERE id = ? AND org_id = ?', [sig, recordId, orgId])
        .catch(() => {}) // silently ignore individual failures
    )).catch(() => {});
  }

  // ── Diagnostic log ──
  console.log('[computeValidScoreMap] diag:', JSON.stringify({
    activityId, orgId,
    rules: ruleRows.length, records: recordRows.length, templates: tplRows.length,
    diag_total, diag_skipped_visible, diag_skipped_noHr, diag_skipped_noRule,
    diag_skipped_noScope, diag_skipped_self, diag_skipped_sig, diag_accepted,
    calcMapSize: calculationMap.size, finalScoreMapSize: finalScoreMap.size,
    invalidClauseKeys: invalidScorerClauseKeys.size, repairMapSize: repairMap.size,
    sigDetails: diag_sigDetails
  }));

  if (options.includeCounts) {
    return { finalScoreMap, submittedByTarget, expectedByCount, scorerExpectedCount };
  }
  return finalScoreMap;
}

module.exports = { applyCalcMethod, computeValidScoreMap };
